version: "3.3"

services:
    postgres:
      image: postgres:13
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
      network_mode: host

    repository:
      build:
        context: ./repository
      ports:
        - "8082:8082"
      depends_on:
        - postgres
      network_mode: host

    products:
      build:
        context: ./products
      ports:
        - "8081:8081"
      depends_on:
        - repository
      network_mode: host

    articles_parsing:
      build:
        context: ./articles_parsing
      ports:
        - "8080:8080"
      depends_on:
        - repository
      network_mode: host

