version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    network_mode: host

  app:
    build: .
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    environment:
      - DB_URL=postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable
    command: /bin/bash -c "./main --cfg=config/config.yaml"
    network_mode: host
